"""Shared infrastructure for RDEBUG Workload Test v1.

Consumes only Semantic API v1 through SessionManager. Collects results into
a global REPORT, verifies evidence integrity, and produces the workload
report + gate. Never modifies Stable Core."""

import json
import os
import random
import re
import subprocess
import sys
import unittest
from collections import Counter, defaultdict
from pathlib import Path

from rdebug import evidence as evidence_mod
from rdebug.analysis.pixel_diff import diff_pixel
from rdebug.analysis.pixel_trace import trace_pixel
from rdebug.analysis.resource_flow import trace_resource
from rdebug.analysis.shader_trace import debug_pixel
from rdebug.session_cache import SessionManager

from . import termination

#: Printed by every scenario on success. Duplicated as a literal in
#: scenarios.py, which is left untouched because it is also the retired
#: scenario's evidence.
SCENARIO_SENTINEL = "SCENARIO_OK"

WORKLOAD_DIR = Path(__file__).parent
CORPUS_DIR = WORKLOAD_DIR / "corpus"
REPORTS_DIR = WORKLOAD_DIR / "reports"

DRAW_COUNTS = [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 10000, 20000]

ENV_DETERMINISM_N = int(os.environ.get("WORKLOAD_DETERMINISM_N", "10"))
ENV_WARM_RUNS = int(os.environ.get("WORKLOAD_WARM_RUNS", "20"))
ENV_STRESS_QUERIES = int(os.environ.get("WORKLOAD_STRESS_QUERIES", "2000"))
ENV_LRU_CYCLES = int(os.environ.get("WORKLOAD_LRU_CYCLES", "12"))
ENV_MCP_CALLS = int(os.environ.get("WORKLOAD_MCP_CALLS", "200"))
ENV_SESSIONS = int(os.environ.get("WORKLOAD_SESSIONS", "25"))


def tier(draws):
    events = draws + 2
    if events < 1000:
        return "S"
    if events < 10000:
        return "M"
    return "L"


def discover_corpus():
    caps = []
    if not CORPUS_DIR.exists():
        return caps
    for p in sorted(CORPUS_DIR.glob("*.rdc")):
        m = re.match(r"w(\d+)", p.stem)
        if not m:
            continue
        caps.append({"path": str(p), "draws": int(m.group(1)),
                     "tier": tier(int(m.group(1)))})
    return caps


CORPUS = discover_corpus()


def pick(prefer_max_draws=None, tier_filter=None):
    candidates = CORPUS
    if tier_filter:
        candidates = [c for c in candidates if c["tier"] == tier_filter]
    if not candidates:
        return None
    if prefer_max_draws is not None:
        fitting = [c for c in candidates if c["draws"] <= prefer_max_draws]
        if fitting:
            return max(fitting, key=lambda c: c["draws"])
    return max(candidates, key=lambda c: c["draws"])


def require_corpus():
    """Runtime skip: corpus may be generated by the runner after import."""

    def decorator(cls):
        original = None
        for klass in cls.__mro__:
            if "setUpClass" in klass.__dict__:
                original = klass.__dict__["setUpClass"]
                break

        def setUpClass(cls_):
            if not CORPUS or not os.environ.get("RDEBUG_RENDERDOC_PATH"):
                raise unittest.SkipTest(
                    "workload corpus (tests/workload/corpus/*.rdc) and "
                    "RDEBUG_RENDERDOC_PATH are required; generate via "
                    "scripts/workload_corpus.py"
                )
            if original is not None:
                original.__func__(cls_)

        cls.setUpClass = classmethod(setUpClass)
        return cls

    return decorator


def spec_for(session, draws):
    last = session.last_draw_event_id()
    pipe = session.pipeline(last)
    target = str(pipe["outputTargets"][0]["resource"])
    covered = (320, 240) if draws >= 1 else None
    background = (10, 10)
    texture = None
    if covered:
        graph = trace_pixel(session, *covered, max_draws=4)
        reads = [e["to"].split(":", 1)[1]
                 for e in graph["edges"] if e["label"] == "reads"]
        texture = reads[0] if reads else None
    return {
        "target": target,
        "texture": texture,
        "covered": covered,
        "background": background,
        "lastDraw": last,
    }


def cheap_plan(session, cap):
    sp = spec_for(session, cap["draws"])
    return [
        ("trace_pixel", lambda: trace_pixel(session, *sp["background"], max_draws=4)),
        ("trace_resource", lambda: trace_resource(session, sp["target"])),
    ]


def full_plan(session, cap, with_debug=True):
    sp = spec_for(session, cap["draws"])
    plan = [
        ("trace_pixel", lambda: trace_pixel(session, *sp["covered"], max_draws=8)),
        ("trace_pixel_bg", lambda: trace_pixel(session, *sp["background"], max_draws=4)),
        ("trace_resource", lambda: trace_resource(session, sp["texture"] or sp["target"])),
        ("diff_pixel", lambda: diff_pixel(
            session, sp["covered"], sp["background"]).to_dict()),
    ]
    if with_debug and cap["draws"] <= 512:
        plan.append(("debug_pixel", lambda: debug_pixel(
            session, *sp["covered"], max_steps=256, include_disassembly=False)))
    return plan


def canonical(obj):
    return json.dumps(obj, sort_keys=True)


def percentile(values, p):
    if not values:
        return None
    values = sorted(values)
    idx = min(len(values) - 1, int(round(p / 100.0 * (len(values) - 1))))
    return round(values[idx], 2)


def verify_evidence(payload, capture_path):
    """Every evidence dict must: carry the current capture, have well-formed
    fields, and reproduce its stable id from its own content."""

    violations = []

    def rebuild(node):
        kwargs = {}
        mapping = (("capture", "capture"), ("eventId", "event_id"),
                   ("resourceId", "resource_id"), ("subresource", "subresource"),
                   ("location", "location"), ("operation", "operation"),
                   ("source", "source"))
        for key, kw in mapping:
            if key in node:
                kwargs[kw] = node[key]
        return evidence_mod.make(**kwargs)["id"]

    def walk(node):
        if isinstance(node, dict):
            if "id" in node and "operation" in node:
                if node.get("capture") != capture_path:
                    violations.append({"issue": "capture_mismatch",
                                       "id": node["id"],
                                       "capture": node.get("capture")})
                if not node.get("operation") or not node.get("source"):
                    violations.append({"issue": "missing_fields",
                                       "id": node["id"]})
                ev = node.get("eventId")
                if ev is not None and not isinstance(ev, int):
                    violations.append({"issue": "bad_event_id", "id": node["id"]})
                if rebuild(node) != node["id"]:
                    violations.append({"issue": "id_mismatch", "id": node["id"]})
            for v in node.values():
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    walk(payload)
    return violations


REPORT = {
    "corpus": [],
    "queries": Counter(),
    "latency": defaultdict(list),
    "unknownLayers": Counter(),
    "evidenceCounts": [],
    "sessions": [],
    "correctness": {},
    "reliability": {"crashes": 0, "unhandledExceptions": 0,
                    "failedRecoveries": 0, "corruptedResponses": 0,
                    "crossCaptureContamination": 0},
    "violations": [],
    # Per-class termination breakdown. Kept OUT of "reliability" on purpose:
    # scripts/workload_run.py does all(v == 0 for v in REPORT["reliability"]),
    # so a nested dict there would silently turn the workload gate False.
    "terminations": {},
    "terminationEvidence": [],
}


def record_query(tool, latency_ms, payload=None, capture=None):
    REPORT["queries"][tool] += 1
    REPORT["latency"][tool].append(round(latency_ms, 2))
    if payload is not None:
        for ly in payload.get("layers", []) or []:
            if ly.get("status") == "unknown":
                REPORT["unknownLayers"][ly["layer"]] += 1
        counter = [0]

        def count(node):
            if isinstance(node, dict):
                if "id" in node and "operation" in node:
                    counter[0] += 1
                for v in node.values():
                    count(v)
            elif isinstance(node, list):
                for v in node:
                    count(v)

        count(payload)
        if counter[0]:
            REPORT["evidenceCounts"].append(counter[0])
        if capture is not None:
            bad = verify_evidence(payload, capture)
            if bad:
                REPORT["violations"].extend(bad)


def record_correctness(name, ok, detail=""):
    REPORT["correctness"][name] = {"pass": bool(ok), "detail": detail}


def record_failure(kind, detail):
    REPORT["reliability"][kind] = REPORT["reliability"].get(kind, 0) + 1
    REPORT["violations"].append({"kind": kind, "detail": detail})


def record_termination(observation):
    """Record how a child ended, by evidence class.

    This is evidence classification, not fault attribution. The class
    native_termination_suspected says the status looked like an unhandled
    native exception; it does not say a crash happened, and
    tests.workload.termination.is_crash exists to keep that honest.
    """
    klass = observation["termination_observation"]["class"]
    REPORT["terminations"][klass] = REPORT["terminations"].get(klass, 0) + 1
    if len(REPORT["terminationEvidence"]) < 100:
        REPORT["terminationEvidence"].append(observation)


def latency_summary():
    return {
        tool: {
            "p50": percentile(v, 50),
            "p95": percentile(v, 95),
            "p99": percentile(v, 99),
            "n": len(v),
        }
        for tool, v in REPORT["latency"].items()
    }


def write_report(gate_pass):
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    out = REPORTS_DIR / "workload-report.json"
    payload = {
        "gate": "PASS" if gate_pass else "FAIL",
        "corpus": REPORT["corpus"],
        "queries": dict(REPORT["queries"]),
        "latency": {
            tool: {
                "p50": percentile(v, 50),
                "p95": percentile(v, 95),
                "p99": percentile(v, 99),
                "n": len(v),
            }
            for tool, v in REPORT["latency"].items()
        },
        "unknownLayers": dict(REPORT["unknownLayers"]),
        "evidenceCountP95": percentile(REPORT["evidenceCounts"], 95),
        "sessions": REPORT["sessions"][:50],
        "correctness": REPORT["correctness"],
        "reliability": REPORT["reliability"],
        "terminations": REPORT["terminations"],
        "terminationEvidence": REPORT["terminationEvidence"][:100],
        "violations": REPORT["violations"][:100],
    }
    with open(out, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
    return payload


def print_summary(payload):
    print("\nRDEBUG WORKLOAD REPORT")
    print("======================")
    print("Corpus   :", len(REPORT["corpus"]), "captures")
    print("Queries  :", dict(REPORT["queries"]))
    for tool, st in payload["latency"].items():
        print(f"  {tool:16s} p50={st['p50']}ms p95={st['p95']}ms "
              f"p99={st['p99']}ms n={st['n']}")
    print("Correctness:")
    for name, r in REPORT["correctness"].items():
        print(f"  {name:24s} {'PASS' if r['pass'] else 'FAIL'} {r['detail']}")
    print("Reliability:", {k: v for k, v in REPORT["reliability"].items()})
    print("Terminations (evidence classes, not fault attribution):",
          {k: v for k, v in REPORT["terminations"].items()})
    print("Unknown layers:", dict(REPORT["unknownLayers"]))
    print("GATE:", payload["gate"])


class WorkloadTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.manager = SessionManager(
            factory_provider=lambda: __import__(
                "rdebug.adapter.core", fromlist=["CaptureSession"]).CaptureSession,
            max_sessions=6,
        )
        random.seed(20260824)

    @classmethod
    def tearDownClass(cls):
        cls.manager.dispose_all()


def run_isolated(scenario, timeout=600):
    """Run a reliability scenario in a fresh subprocess and observe how it ended.

    A timeout is recorded rather than re-raised. subprocess.TimeoutExpired
    carries no .returncode at all, and this used to let it escape: the child was
    killed and REPORT["reliability"] received no entry, so the one failure mode
    that certainly occurred was invisible to the report.

    The returncode is handed back exactly as the OS gave it, including None for
    a timeout. Nothing is normalised here; classification lives in
    tests.workload.termination.
    """

    root = Path(__file__).parent.parent.parent
    env = dict(os.environ)
    env["PYTHONPATH"] = (
        str(root / "src") + os.pathsep + str(root / "tests")
        + os.pathsep + env.get("PYTHONPATH", "")
    )
    cmd = [sys.executable, "-m", "tests.workload.isolated_runner", scenario]
    try:
        proc = subprocess.run(
            cmd, env=env, capture_output=True, text=True, timeout=timeout,
            cwd=str(root),
        )
    except subprocess.TimeoutExpired as exc:
        stdout = exc.stdout or ""
        if isinstance(stdout, bytes):
            stdout = stdout.decode("utf-8", "replace")
        stderr = exc.stderr or b""
        if isinstance(stderr, bytes):
            stderr = stderr.decode("utf-8", "replace")
        return {
            "returncode": None,
            "stdout": stdout,
            "stderr": stderr,
            "observation": termination.observe_from_timeout(exc),
            "timed_out": True,
        }
    stderr = proc.stderr or ""
    observation = termination.observe(returncode=proc.returncode,
                                      stdout=proc.stdout or "",
                                      stderr=stderr,
                                      sentinel=SCENARIO_SENTINEL)
    return {
        "returncode": proc.returncode,
        "stdout": proc.stdout or "",
        "stderr": stderr,
        "observation": observation,
        "timed_out": False,
    }
